service: webtldr-express-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    GEMINI_API_KEY: ${env:GEMINI_API_KEY} # Uses your local .env

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env
